; Fabric CNC Toolpath
; Generated by ToolpathGenerator
; Machine homing is automatically verified before execution

G20 ; Set units to inches
G90 ; Set absolute positioning
G54 ; Use work coordinate system (WCS)
G17 ; Select XY plane
G94 ; Feed rate mode (units per minute)

G0 Z-2.0 ; Move to safe height

; Shape: merged_shape_1
G0 X21.000 Y22.938 ; Move to start
G0 A-0.2682 ; Set initial blade angle
G0 Z-2.0 ; Plunge to cutting height
G1 X20.836 Y22.919 A-0.2682 F6000.0 ; Cut to next point
G1 X20.704 Y22.905 A-0.2669 F6000.0 ; Cut to next point
G1 X20.573 Y22.892 A-0.2658 F6000.0 ; Cut to next point
G1 X20.441 Y22.880 A-0.2647 F6000.0 ; Cut to next point
G1 X20.309 Y22.868 A-0.2636 F6000.0 ; Cut to next point
G1 X20.177 Y22.858 A-0.2625 F6000.0 ; Cut to next point
G1 X20.045 Y22.848 A-0.2614 F6000.0 ; Cut to next point
G1 X19.914 Y22.840 A-0.2603 F6000.0 ; Cut to next point
G1 X19.781 Y22.832 A-0.2591 F6000.0 ; Cut to next point
G1 X19.649 Y22.826 A-0.2580 F6000.0 ; Cut to next point
G1 X19.517 Y22.820 A-0.2569 F6000.0 ; Cut to next point
G1 X19.385 Y22.815 A-0.2558 F6000.0 ; Cut to next point
G1 X19.253 Y22.811 A-0.2547 F6000.0 ; Cut to next point
G1 X19.121 Y22.808 A-0.2536 F6000.0 ; Cut to next point
G1 X18.988 Y22.806 A-0.2525 F6000.0 ; Cut to next point
G1 X18.856 Y22.805 A-0.2514 F6000.0 ; Cut to next point
G1 X18.724 Y22.805 A-0.2502 F6000.0 ; Cut to next point
G1 X18.592 Y22.806 A-0.2491 F6000.0 ; Cut to next point
G1 X18.460 Y22.807 A-0.2480 F6000.0 ; Cut to next point
G1 X18.327 Y22.810 A-0.2469 F6000.0 ; Cut to next point
G1 X18.195 Y22.813 A-0.2458 F6000.0 ; Cut to next point
G1 X18.063 Y22.818 A-0.2447 F6000.0 ; Cut to next point
G1 X17.931 Y22.823 A-0.2436 F6000.0 ; Cut to next point
G1 X17.799 Y22.829 A-0.2425 F6000.0 ; Cut to next point
G1 X17.667 Y22.836 A-0.2414 F6000.0 ; Cut to next point
G1 X17.535 Y22.845 A-0.2402 F6000.0 ; Cut to next point
G1 X17.403 Y22.854 A-0.2391 F6000.0 ; Cut to next point
G1 X17.271 Y22.864 A-0.2380 F6000.0 ; Cut to next point
G1 X17.139 Y22.874 A-0.2369 F6000.0 ; Cut to next point
G1 X17.007 Y22.886 A-0.2358 F6000.0 ; Cut to next point
G1 X16.876 Y22.899 A-0.2347 F6000.0 ; Cut to next point
G1 X16.744 Y22.913 A-0.2336 F6000.0 ; Cut to next point
G1 X16.613 Y22.927 A-0.2325 F6000.0 ; Cut to next point
G1 X16.481 Y22.943 A-0.2313 F6000.0 ; Cut to next point
G1 X16.350 Y22.959 A-0.2302 F6000.0 ; Cut to next point
G1 X16.219 Y22.976 A-0.2291 F6000.0 ; Cut to next point
G1 X16.088 Y22.994 A-0.2280 F6000.0 ; Cut to next point
G1 X15.957 Y23.014 A-0.2269 F6000.0 ; Cut to next point
G1 X15.826 Y23.034 A-0.2258 F6000.0 ; Cut to next point
G1 X15.696 Y23.055 A-0.2247 F6000.0 ; Cut to next point
G1 X15.565 Y23.076 A-0.2236 F6000.0 ; Cut to next point
G1 X15.435 Y23.099 A-0.2224 F6000.0 ; Cut to next point
G1 X15.305 Y23.123 A-0.2213 F6000.0 ; Cut to next point
G1 X15.175 Y23.148 A-0.2202 F6000.0 ; Cut to next point
G1 X15.045 Y23.173 A-0.2191 F6000.0 ; Cut to next point
G1 X14.916 Y23.199 A-0.2180 F6000.0 ; Cut to next point
G1 X14.786 Y23.227 A-0.2169 F6000.0 ; Cut to next point
G1 X14.657 Y23.255 A-0.2158 F6000.0 ; Cut to next point
G1 X14.528 Y23.284 A-0.2147 F6000.0 ; Cut to next point
G1 X14.399 Y23.314 A-0.2136 F6000.0 ; Cut to next point
G1 X14.271 Y23.345 A-0.2124 F6000.0 ; Cut to next point
G1 X14.142 Y23.377 A-0.2113 F6000.0 ; Cut to next point
G1 X14.014 Y23.410 A-0.2102 F6000.0 ; Cut to next point
G1 X13.886 Y23.443 A-0.2091 F6000.0 ; Cut to next point
G1 X13.759 Y23.478 A-0.2080 F6000.0 ; Cut to next point
G1 X13.631 Y23.513 A-0.2069 F6000.0 ; Cut to next point
G1 X13.504 Y23.549 A-0.2058 F6000.0 ; Cut to next point
G1 X13.377 Y23.587 A-0.2047 F6000.0 ; Cut to next point
G1 X13.251 Y23.625 A-0.2035 F6000.0 ; Cut to next point
G1 X13.124 Y23.664 A-0.2024 F6000.0 ; Cut to next point
G1 X12.998 Y23.703 A-0.2013 F6000.0 ; Cut to next point
G1 X12.872 Y23.744 A-0.2002 F6000.0 ; Cut to next point
G1 X12.747 Y23.786 A-0.1991 F6000.0 ; Cut to next point
G1 X12.621 Y23.828 A-0.1980 F6000.0 ; Cut to next point
G1 X12.497 Y23.871 A-0.1969 F6000.0 ; Cut to next point
G1 X12.372 Y23.916 A-0.1958 F6000.0 ; Cut to next point
G1 X12.248 Y23.961 A-0.1947 F6000.0 ; Cut to next point
G1 X12.124 Y24.007 A-0.1935 F6000.0 ; Cut to next point
G1 X12.000 Y24.053 A-0.1924 F6000.0 ; Cut to next point
G1 X11.876 Y24.101 A-0.1913 F6000.0 ; Cut to next point
G1 X11.753 Y24.150 A-0.1902 F6000.0 ; Cut to next point
G1 X11.631 Y24.199 A-0.1891 F6000.0 ; Cut to next point
G1 X11.508 Y24.249 A-0.1880 F6000.0 ; Cut to next point
G1 X11.386 Y24.300 A-0.1869 F6000.0 ; Cut to next point
G1 X11.265 Y24.352 A-0.1858 F6000.0 ; Cut to next point
G1 X11.144 Y24.405 A-0.1846 F6000.0 ; Cut to next point
G1 X11.023 Y24.459 A-0.1835 F6000.0 ; Cut to next point
G1 X10.902 Y24.513 A-0.1824 F6000.0 ; Cut to next point
G1 X10.782 Y24.568 A-0.1813 F6000.0 ; Cut to next point
G1 X10.662 Y24.625 A-0.1802 F6000.0 ; Cut to next point
G1 X10.543 Y24.682 A-0.1791 F6000.0 ; Cut to next point
G1 X10.424 Y24.739 A-0.1780 F6000.0 ; Cut to next point
G1 X10.306 Y24.798 A-0.1769 F6000.0 ; Cut to next point
G1 X10.187 Y24.858 A-0.1757 F6000.0 ; Cut to next point
G1 X10.070 Y24.918 A-0.1746 F6000.0 ; Cut to next point
G1 X9.952 Y24.979 A-0.1735 F6000.0 ; Cut to next point
G1 X9.836 Y25.041 A-0.1724 F6000.0 ; Cut to next point
G1 X9.719 Y25.104 A-0.1713 F6000.0 ; Cut to next point
G1 X9.603 Y25.167 A-0.1702 F6000.0 ; Cut to next point
G1 X9.488 Y25.232 A-0.1691 F6000.0 ; Cut to next point
G1 X9.373 Y25.297 A-0.1680 F6000.0 ; Cut to next point
G1 X9.258 Y25.363 A-0.1669 F6000.0 ; Cut to next point
G1 X9.144 Y25.430 A-0.1657 F6000.0 ; Cut to next point
G1 X9.030 Y25.497 A-0.1646 F6000.0 ; Cut to next point
G1 X8.917 Y25.566 A-0.1635 F6000.0 ; Cut to next point
G1 X8.804 Y25.635 A-0.1624 F6000.0 ; Cut to next point
G1 X8.692 Y25.705 A-0.1613 F6000.0 ; Cut to next point
G1 X8.580 Y25.775 A-0.1602 F6000.0 ; Cut to next point
G1 X8.469 Y25.847 A-0.1591 F6000.0 ; Cut to next point
G1 X8.358 Y25.919 A-0.1580 F6000.0 ; Cut to next point
G1 X8.248 Y25.992 A-0.1568 F6000.0 ; Cut to next point
G1 X8.138 Y26.066 A-0.1557 F6000.0 ; Cut to next point
G1 X8.029 Y26.141 A-0.1546 F6000.0 ; Cut to next point
G1 X7.921 Y26.216 A-0.1535 F6000.0 ; Cut to next point
G1 X7.812 Y26.292 A-0.1524 F6000.0 ; Cut to next point
G1 X7.705 Y26.369 A-0.1513 F6000.0 ; Cut to next point
G1 X7.598 Y26.447 A-0.1502 F6000.0 ; Cut to next point
G1 X7.491 Y26.525 A-0.1491 F6000.0 ; Cut to next point
G1 X7.385 Y26.604 A-0.1480 F6000.0 ; Cut to next point
G1 X7.280 Y26.684 A-0.1468 F6000.0 ; Cut to next point
G1 X7.175 Y26.765 A-0.1457 F6000.0 ; Cut to next point
G1 X7.071 Y26.846 A-0.1446 F6000.0 ; Cut to next point
G1 X6.967 Y26.928 A-0.1435 F6000.0 ; Cut to next point
G1 X6.864 Y27.011 A-0.1424 F6000.0 ; Cut to next point
G1 X6.761 Y27.094 A-0.1413 F6000.0 ; Cut to next point
G1 X6.659 Y27.178 A-0.1402 F6000.0 ; Cut to next point
G1 X6.558 Y27.263 A-0.1391 F6000.0 ; Cut to next point
G1 X6.457 Y27.349 A-0.1379 F6000.0 ; Cut to next point
G1 X6.357 Y27.435 A-0.1368 F6000.0 ; Cut to next point
G1 X6.257 Y27.522 A-0.1357 F6000.0 ; Cut to next point
G1 X6.158 Y27.610 A-0.1346 F6000.0 ; Cut to next point
G1 X6.060 Y27.698 A-0.1335 F6000.0 ; Cut to next point
G1 X5.962 Y27.787 A-0.1324 F6000.0 ; Cut to next point
G1 X5.865 Y27.877 A-0.1313 F6000.0 ; Cut to next point
G1 X5.768 Y27.967 A-0.1302 F6000.0 ; Cut to next point
G1 X5.673 Y28.059 A-0.1290 F6000.0 ; Cut to next point
G1 X5.577 Y28.150 A-0.1279 F6000.0 ; Cut to next point
G1 X5.483 Y28.243 A-0.1268 F6000.0 ; Cut to next point
G1 X5.389 Y28.336 A-0.1257 F6000.0 ; Cut to next point
G1 X5.296 Y28.430 A-0.1246 F6000.0 ; Cut to next point
G1 X5.203 Y28.524 A-0.1235 F6000.0 ; Cut to next point
G1 X5.111 Y28.619 A-0.1224 F6000.0 ; Cut to next point
G1 X5.020 Y28.715 A-0.1213 F6000.0 ; Cut to next point
G1 X4.929 Y28.811 A-0.1202 F6000.0 ; Cut to next point
G1 X4.839 Y28.908 A-0.1190 F6000.0 ; Cut to next point
G1 X4.750 Y29.006 A-0.1179 F6000.0 ; Cut to next point
G1 X4.661 Y29.104 A-0.1168 F6000.0 ; Cut to next point
G1 X4.573 Y29.203 A-0.1157 F6000.0 ; Cut to next point
G1 X4.486 Y29.302 A-0.1146 F6000.0 ; Cut to next point
G1 X4.400 Y29.402 A-0.1135 F6000.0 ; Cut to next point
G1 X4.314 Y29.503 A-0.1124 F6000.0 ; Cut to next point
G1 X4.229 Y29.604 A-0.1113 F6000.0 ; Cut to next point
G1 X4.144 Y29.706 A-0.1101 F6000.0 ; Cut to next point
G1 X4.061 Y29.808 A-0.1090 F6000.0 ; Cut to next point
G1 X3.978 Y29.911 A-0.1079 F6000.0 ; Cut to next point
G1 X3.895 Y30.015 A-0.1068 F6000.0 ; Cut to next point
G1 X3.814 Y30.119 A-0.1057 F6000.0 ; Cut to next point
G1 X3.733 Y30.224 A-0.1046 F6000.0 ; Cut to next point
G1 X3.653 Y30.329 A-0.1035 F6000.0 ; Cut to next point
G1 X3.574 Y30.435 A-0.1024 F6000.0 ; Cut to next point
G1 X3.495 Y30.541 A-0.1013 F6000.0 ; Cut to next point
G1 X3.417 Y30.648 A-0.1001 F6000.0 ; Cut to next point
G1 X3.340 Y30.755 A-0.0990 F6000.0 ; Cut to next point
G1 X3.264 Y30.863 A-0.0979 F6000.0 ; Cut to next point
G1 X3.188 Y30.972 A-0.0968 F6000.0 ; Cut to next point
G1 X3.114 Y31.081 A-0.0957 F6000.0 ; Cut to next point
G1 X3.040 Y31.191 A-0.0946 F6000.0 ; Cut to next point
G1 X2.966 Y31.301 A-0.0935 F6000.0 ; Cut to next point
G1 X2.894 Y31.411 A-0.0924 F6000.0 ; Cut to next point
G1 X2.822 Y31.522 A-0.0912 F6000.0 ; Cut to next point
G1 X2.751 Y31.634 A-0.0901 F6000.0 ; Cut to next point
G1 X2.681 Y31.746 A-0.0890 F6000.0 ; Cut to next point
G1 X2.612 Y31.859 A-0.0879 F6000.0 ; Cut to next point
G1 X2.543 Y31.972 A-0.0868 F6000.0 ; Cut to next point
G1 X2.475 Y32.085 A-0.0857 F6000.0 ; Cut to next point
G1 X2.408 Y32.199 A-0.0846 F6000.0 ; Cut to next point
G1 X2.342 Y32.314 A-0.0835 F6000.0 ; Cut to next point
G1 X2.277 Y32.429 A-0.0824 F6000.0 ; Cut to next point
G1 X2.212 Y32.544 A-0.0812 F6000.0 ; Cut to next point
G1 X2.148 Y32.660 A-0.0801 F6000.0 ; Cut to next point
G1 X2.085 Y32.776 A-0.0790 F6000.0 ; Cut to next point
G1 X2.023 Y32.893 A-0.0779 F6000.0 ; Cut to next point
G1 X1.962 Y33.010 A-0.0768 F6000.0 ; Cut to next point
G1 X1.901 Y33.128 A-0.0757 F6000.0 ; Cut to next point
G1 X1.841 Y33.246 A-0.0746 F6000.0 ; Cut to next point
G1 X1.782 Y33.364 A-0.0735 F6000.0 ; Cut to next point
G1 X1.724 Y33.483 A-0.0723 F6000.0 ; Cut to next point
G1 X1.667 Y33.602 A-0.0712 F6000.0 ; Cut to next point
G1 X1.611 Y33.722 A-0.0701 F6000.0 ; Cut to next point
G1 X1.555 Y33.842 A-0.0690 F6000.0 ; Cut to next point
G1 X1.500 Y33.962 A-0.0679 F6000.0 ; Cut to next point
G1 X1.447 Y34.083 A-0.0668 F6000.0 ; Cut to next point
G1 X1.394 Y34.204 A-0.0657 F6000.0 ; Cut to next point
G1 X1.341 Y34.325 A-0.0646 F6000.0 ; Cut to next point
G1 X1.290 Y34.447 A-0.0634 F6000.0 ; Cut to next point
G1 X1.240 Y34.570 A-0.0623 F6000.0 ; Cut to next point
G1 X1.190 Y34.692 A-0.0612 F6000.0 ; Cut to next point
G1 X1.141 Y34.815 A-0.0601 F6000.0 ; Cut to next point
G1 X1.093 Y34.938 A-0.0590 F6000.0 ; Cut to next point
G1 X1.046 Y35.062 A-0.0579 F6000.0 ; Cut to next point
G1 X1.000 Y35.186 A-0.0568 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-0.5000 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X1.000 Y3.000 A-0.5000 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-0.7500 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X21.000 Y3.000 A-0.7500 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-1.0000 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X21.000 Y22.938 A-1.0000 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise tool to safe height

; Shape: merged_shape_0
G0 X53.989 Y35.155 ; Move to start
G0 A-0.4429 ; Set initial blade angle
G0 Z-2.0 ; Plunge to cutting height
G1 X53.942 Y35.031 A-0.4429 F6000.0 ; Cut to next point
G1 X53.895 Y34.908 A-0.4418 F6000.0 ; Cut to next point
G1 X53.847 Y34.784 A-0.4407 F6000.0 ; Cut to next point
G1 X53.798 Y34.661 A-0.4396 F6000.0 ; Cut to next point
G1 X53.748 Y34.539 A-0.4385 F6000.0 ; Cut to next point
G1 X53.697 Y34.417 A-0.4374 F6000.0 ; Cut to next point
G1 X53.646 Y34.295 A-0.4363 F6000.0 ; Cut to next point
G1 X53.593 Y34.174 A-0.4352 F6000.0 ; Cut to next point
G1 X53.540 Y34.053 A-0.4341 F6000.0 ; Cut to next point
G1 X53.486 Y33.932 A-0.4329 F6000.0 ; Cut to next point
G1 X53.431 Y33.812 A-0.4318 F6000.0 ; Cut to next point
G1 X53.375 Y33.692 A-0.4307 F6000.0 ; Cut to next point
G1 X53.319 Y33.572 A-0.4296 F6000.0 ; Cut to next point
G1 X53.261 Y33.453 A-0.4285 F6000.0 ; Cut to next point
G1 X53.203 Y33.334 A-0.4274 F6000.0 ; Cut to next point
G1 X53.144 Y33.216 A-0.4263 F6000.0 ; Cut to next point
G1 X53.084 Y33.098 A-0.4252 F6000.0 ; Cut to next point
G1 X53.023 Y32.981 A-0.4240 F6000.0 ; Cut to next point
G1 X52.962 Y32.864 A-0.4229 F6000.0 ; Cut to next point
G1 X52.899 Y32.747 A-0.4218 F6000.0 ; Cut to next point
G1 X52.836 Y32.631 A-0.4207 F6000.0 ; Cut to next point
G1 X52.772 Y32.515 A-0.4196 F6000.0 ; Cut to next point
G1 X52.707 Y32.400 A-0.4185 F6000.0 ; Cut to next point
G1 X52.642 Y32.285 A-0.4174 F6000.0 ; Cut to next point
G1 X52.575 Y32.171 A-0.4163 F6000.0 ; Cut to next point
G1 X52.508 Y32.057 A-0.4151 F6000.0 ; Cut to next point
G1 X52.440 Y31.943 A-0.4140 F6000.0 ; Cut to next point
G1 X52.371 Y31.830 A-0.4129 F6000.0 ; Cut to next point
G1 X52.302 Y31.718 A-0.4118 F6000.0 ; Cut to next point
G1 X52.231 Y31.606 A-0.4107 F6000.0 ; Cut to next point
G1 X52.160 Y31.494 A-0.4096 F6000.0 ; Cut to next point
G1 X52.088 Y31.384 A-0.4085 F6000.0 ; Cut to next point
G1 X52.015 Y31.273 A-0.4074 F6000.0 ; Cut to next point
G1 X51.942 Y31.163 A-0.4063 F6000.0 ; Cut to next point
G1 X51.868 Y31.054 A-0.4051 F6000.0 ; Cut to next point
G1 X51.793 Y30.945 A-0.4040 F6000.0 ; Cut to next point
G1 X51.717 Y30.836 A-0.4029 F6000.0 ; Cut to next point
G1 X51.640 Y30.728 A-0.4018 F6000.0 ; Cut to next point
G1 X51.563 Y30.621 A-0.4007 F6000.0 ; Cut to next point
G1 X51.485 Y30.514 A-0.3996 F6000.0 ; Cut to next point
G1 X51.406 Y30.408 A-0.3985 F6000.0 ; Cut to next point
G1 X51.327 Y30.302 A-0.3974 F6000.0 ; Cut to next point
G1 X51.247 Y30.197 A-0.3962 F6000.0 ; Cut to next point
G1 X51.166 Y30.093 A-0.3951 F6000.0 ; Cut to next point
G1 X51.084 Y29.989 A-0.3940 F6000.0 ; Cut to next point
G1 X51.002 Y29.885 A-0.3929 F6000.0 ; Cut to next point
G1 X50.918 Y29.782 A-0.3918 F6000.0 ; Cut to next point
G1 X50.835 Y29.680 A-0.3907 F6000.0 ; Cut to next point
G1 X50.750 Y29.579 A-0.3896 F6000.0 ; Cut to next point
G1 X50.665 Y29.477 A-0.3885 F6000.0 ; Cut to next point
G1 X50.579 Y29.377 A-0.3874 F6000.0 ; Cut to next point
G1 X50.492 Y29.277 A-0.3862 F6000.0 ; Cut to next point
G1 X50.405 Y29.178 A-0.3851 F6000.0 ; Cut to next point
G1 X50.317 Y29.079 A-0.3840 F6000.0 ; Cut to next point
G1 X50.228 Y28.981 A-0.3829 F6000.0 ; Cut to next point
G1 X50.138 Y28.884 A-0.3818 F6000.0 ; Cut to next point
G1 X50.048 Y28.787 A-0.3807 F6000.0 ; Cut to next point
G1 X49.958 Y28.691 A-0.3796 F6000.0 ; Cut to next point
G1 X49.866 Y28.595 A-0.3785 F6000.0 ; Cut to next point
G1 X49.774 Y28.500 A-0.3773 F6000.0 ; Cut to next point
G1 X49.681 Y28.406 A-0.3762 F6000.0 ; Cut to next point
G1 X49.588 Y28.313 A-0.3751 F6000.0 ; Cut to next point
G1 X49.494 Y28.220 A-0.3740 F6000.0 ; Cut to next point
G1 X49.399 Y28.127 A-0.3729 F6000.0 ; Cut to next point
G1 X49.304 Y28.036 A-0.3718 F6000.0 ; Cut to next point
G1 X49.207 Y27.945 A-0.3707 F6000.0 ; Cut to next point
G1 X49.111 Y27.855 A-0.3696 F6000.0 ; Cut to next point
G1 X49.014 Y27.765 A-0.3684 F6000.0 ; Cut to next point
G1 X48.916 Y27.676 A-0.3673 F6000.0 ; Cut to next point
G1 X48.817 Y27.588 A-0.3662 F6000.0 ; Cut to next point
G1 X48.718 Y27.500 A-0.3651 F6000.0 ; Cut to next point
G1 X48.618 Y27.413 A-0.3640 F6000.0 ; Cut to next point
G1 X48.518 Y27.327 A-0.3629 F6000.0 ; Cut to next point
G1 X48.417 Y27.242 A-0.3618 F6000.0 ; Cut to next point
G1 X48.315 Y27.157 A-0.3607 F6000.0 ; Cut to next point
G1 X48.213 Y27.073 A-0.3596 F6000.0 ; Cut to next point
G1 X48.111 Y26.990 A-0.3584 F6000.0 ; Cut to next point
G1 X48.007 Y26.907 A-0.3573 F6000.0 ; Cut to next point
G1 X47.903 Y26.825 A-0.3562 F6000.0 ; Cut to next point
G1 X47.799 Y26.744 A-0.3551 F6000.0 ; Cut to next point
G1 X47.694 Y26.664 A-0.3540 F6000.0 ; Cut to next point
G1 X47.588 Y26.584 A-0.3529 F6000.0 ; Cut to next point
G1 X47.482 Y26.505 A-0.3518 F6000.0 ; Cut to next point
G1 X47.376 Y26.427 A-0.3507 F6000.0 ; Cut to next point
G1 X47.268 Y26.350 A-0.3495 F6000.0 ; Cut to next point
G1 X47.161 Y26.273 A-0.3484 F6000.0 ; Cut to next point
G1 X47.052 Y26.197 A-0.3473 F6000.0 ; Cut to next point
G1 X46.944 Y26.122 A-0.3462 F6000.0 ; Cut to next point
G1 X46.834 Y26.048 A-0.3451 F6000.0 ; Cut to next point
G1 X46.724 Y25.974 A-0.3440 F6000.0 ; Cut to next point
G1 X46.614 Y25.901 A-0.3429 F6000.0 ; Cut to next point
G1 X46.503 Y25.829 A-0.3418 F6000.0 ; Cut to next point
G1 X46.392 Y25.758 A-0.3407 F6000.0 ; Cut to next point
G1 X46.280 Y25.687 A-0.3395 F6000.0 ; Cut to next point
G1 X46.168 Y25.617 A-0.3384 F6000.0 ; Cut to next point
G1 X46.055 Y25.548 A-0.3373 F6000.0 ; Cut to next point
G1 X45.941 Y25.480 A-0.3362 F6000.0 ; Cut to next point
G1 X45.828 Y25.413 A-0.3351 F6000.0 ; Cut to next point
G1 X45.713 Y25.346 A-0.3340 F6000.0 ; Cut to next point
G1 X45.599 Y25.281 A-0.3329 F6000.0 ; Cut to next point
G1 X45.483 Y25.216 A-0.3318 F6000.0 ; Cut to next point
G1 X45.368 Y25.151 A-0.3306 F6000.0 ; Cut to next point
G1 X45.252 Y25.088 A-0.3295 F6000.0 ; Cut to next point
G1 X45.135 Y25.025 A-0.3284 F6000.0 ; Cut to next point
G1 X45.018 Y24.964 A-0.3273 F6000.0 ; Cut to next point
G1 X44.901 Y24.903 A-0.3262 F6000.0 ; Cut to next point
G1 X44.783 Y24.843 A-0.3251 F6000.0 ; Cut to next point
G1 X44.665 Y24.783 A-0.3240 F6000.0 ; Cut to next point
G1 X44.546 Y24.725 A-0.3229 F6000.0 ; Cut to next point
G1 X44.427 Y24.667 A-0.3217 F6000.0 ; Cut to next point
G1 X44.308 Y24.611 A-0.3206 F6000.0 ; Cut to next point
G1 X44.188 Y24.555 A-0.3195 F6000.0 ; Cut to next point
G1 X44.068 Y24.499 A-0.3184 F6000.0 ; Cut to next point
G1 X43.947 Y24.445 A-0.3173 F6000.0 ; Cut to next point
G1 X43.826 Y24.392 A-0.3162 F6000.0 ; Cut to next point
G1 X43.705 Y24.339 A-0.3151 F6000.0 ; Cut to next point
G1 X43.583 Y24.287 A-0.3140 F6000.0 ; Cut to next point
G1 X43.461 Y24.237 A-0.3129 F6000.0 ; Cut to next point
G1 X43.339 Y24.187 A-0.3117 F6000.0 ; Cut to next point
G1 X43.216 Y24.137 A-0.3106 F6000.0 ; Cut to next point
G1 X43.093 Y24.089 A-0.3095 F6000.0 ; Cut to next point
G1 X42.969 Y24.042 A-0.3084 F6000.0 ; Cut to next point
G1 X42.846 Y23.995 A-0.3073 F6000.0 ; Cut to next point
G1 X42.721 Y23.949 A-0.3062 F6000.0 ; Cut to next point
G1 X42.597 Y23.904 A-0.3051 F6000.0 ; Cut to next point
G1 X42.472 Y23.860 A-0.3040 F6000.0 ; Cut to next point
G1 X42.347 Y23.817 A-0.3028 F6000.0 ; Cut to next point
G1 X42.222 Y23.775 A-0.3017 F6000.0 ; Cut to next point
G1 X42.096 Y23.734 A-0.3006 F6000.0 ; Cut to next point
G1 X41.970 Y23.693 A-0.2995 F6000.0 ; Cut to next point
G1 X41.844 Y23.654 A-0.2984 F6000.0 ; Cut to next point
G1 X41.718 Y23.615 A-0.2973 F6000.0 ; Cut to next point
G1 X41.591 Y23.577 A-0.2962 F6000.0 ; Cut to next point
G1 X41.464 Y23.540 A-0.2951 F6000.0 ; Cut to next point
G1 X41.337 Y23.504 A-0.2940 F6000.0 ; Cut to next point
G1 X41.209 Y23.469 A-0.2928 F6000.0 ; Cut to next point
G1 X41.082 Y23.435 A-0.2917 F6000.0 ; Cut to next point
G1 X40.954 Y23.401 A-0.2906 F6000.0 ; Cut to next point
G1 X40.825 Y23.369 A-0.2895 F6000.0 ; Cut to next point
G1 X40.697 Y23.337 A-0.2884 F6000.0 ; Cut to next point
G1 X40.568 Y23.307 A-0.2873 F6000.0 ; Cut to next point
G1 X40.440 Y23.277 A-0.2862 F6000.0 ; Cut to next point
G1 X40.311 Y23.248 A-0.2851 F6000.0 ; Cut to next point
G1 X40.181 Y23.220 A-0.2839 F6000.0 ; Cut to next point
G1 X40.052 Y23.193 A-0.2828 F6000.0 ; Cut to next point
G1 X39.922 Y23.167 A-0.2817 F6000.0 ; Cut to next point
G1 X39.792 Y23.141 A-0.2806 F6000.0 ; Cut to next point
G1 X39.662 Y23.117 A-0.2795 F6000.0 ; Cut to next point
G1 X39.532 Y23.093 A-0.2784 F6000.0 ; Cut to next point
G1 X39.402 Y23.071 A-0.2773 F6000.0 ; Cut to next point
G1 X39.272 Y23.049 A-0.2762 F6000.0 ; Cut to next point
G1 X39.141 Y23.029 A-0.2750 F6000.0 ; Cut to next point
G1 X39.010 Y23.009 A-0.2739 F6000.0 ; Cut to next point
G1 X38.879 Y22.990 A-0.2728 F6000.0 ; Cut to next point
G1 X38.748 Y22.972 A-0.2717 F6000.0 ; Cut to next point
G1 X38.617 Y22.955 A-0.2706 F6000.0 ; Cut to next point
G1 X38.486 Y22.939 A-0.2695 F6000.0 ; Cut to next point
G1 X38.354 Y22.923 A-0.2684 F6000.0 ; Cut to next point
G1 X38.223 Y22.909 A-0.2673 F6000.0 ; Cut to next point
G1 X38.091 Y22.896 A-0.2662 F6000.0 ; Cut to next point
G1 X37.960 Y22.883 A-0.2650 F6000.0 ; Cut to next point
G1 X37.828 Y22.872 A-0.2639 F6000.0 ; Cut to next point
G1 X37.696 Y22.861 A-0.2628 F6000.0 ; Cut to next point
G1 X37.564 Y22.851 A-0.2617 F6000.0 ; Cut to next point
G1 X37.432 Y22.842 A-0.2606 F6000.0 ; Cut to next point
G1 X37.300 Y22.835 A-0.2595 F6000.0 ; Cut to next point
G1 X37.168 Y22.828 A-0.2584 F6000.0 ; Cut to next point
G1 X37.036 Y22.822 A-0.2573 F6000.0 ; Cut to next point
G1 X36.904 Y22.817 A-0.2561 F6000.0 ; Cut to next point
G1 X36.772 Y22.812 A-0.2550 F6000.0 ; Cut to next point
G1 X36.640 Y22.809 A-0.2539 F6000.0 ; Cut to next point
G1 X36.507 Y22.807 A-0.2528 F6000.0 ; Cut to next point
G1 X36.375 Y22.805 A-0.2517 F6000.0 ; Cut to next point
G1 X36.243 Y22.805 A-0.2506 F6000.0 ; Cut to next point
G1 X36.111 Y22.805 A-0.2495 F6000.0 ; Cut to next point
G1 X35.978 Y22.807 A-0.2484 F6000.0 ; Cut to next point
G1 X35.846 Y22.809 A-0.2473 F6000.0 ; Cut to next point
G1 X35.714 Y22.812 A-0.2461 F6000.0 ; Cut to next point
G1 X35.582 Y22.816 A-0.2450 F6000.0 ; Cut to next point
G1 X35.450 Y22.821 A-0.2439 F6000.0 ; Cut to next point
G1 X35.318 Y22.827 A-0.2428 F6000.0 ; Cut to next point
G1 X35.186 Y22.834 A-0.2417 F6000.0 ; Cut to next point
G1 X35.053 Y22.842 A-0.2406 F6000.0 ; Cut to next point
G1 X34.922 Y22.851 A-0.2395 F6000.0 ; Cut to next point
G1 X34.790 Y22.860 A-0.2384 F6000.0 ; Cut to next point
G1 X34.658 Y22.871 A-0.2372 F6000.0 ; Cut to next point
G1 X34.526 Y22.883 A-0.2361 F6000.0 ; Cut to next point
G1 X34.394 Y22.895 A-0.2350 F6000.0 ; Cut to next point
G1 X34.263 Y22.908 A-0.2339 F6000.0 ; Cut to next point
G1 X34.131 Y22.923 A-0.2328 F6000.0 ; Cut to next point
G1 X34.000 Y22.938 A-0.2317 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-0.5000 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X34.000 Y3.000 A-0.5000 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-0.7500 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X54.000 Y3.000 A-0.7500 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise Z for corner
G0 A-1.0000 ; Rotate blade for new direction
G0 Z-2.0 ; Lower Z to cutting height
G1 X54.000 Y35.186 A-1.0000 F6000.0 ; Cut to next point
G0 Z-2.0 ; Raise tool to safe height


G0 Z-2.0 ; Return to safe height
G0 X0 Y0 A0 ; Return to work coordinate origin
M5 ; Spindle off (if applicable)
M2 ; End program